### ISSUE TITLE
USB mode requires some fixes

### ISSUE THREAD

**Issue by ahilevich** [BrianPeek/legoev3#17]
Guys, I figured out how to make SDK work properly with brick via USB.
1) All commands should wait reply (even DirectNoReplay and SystemNoReply types)
2) Sensor reading subroutine should be turned off. Or it should be synchronized to prevent reading while a command is running or waiting for reply.

**Comment by geekygravity** [comment]
Hi, just following up on this. Sounds similar to the KeyNotFoundException issue #7. Is that why it was closed? Thanks.
