### ISSUE TITLE
Add blocking methods

### ISSUE THREAD

**Issue by miloush** [BrianPeek/legoev3#19]
This is a great library but cumbersome to use in console apps. Please consider adding blocking methods for the desktop version.

**Comment by BrianPeek** [comment]
There is a sample showing how to use in a Console project...making non-async versions of all methods is not something I plan on creating at this time. Thanks!

https://github.com/BrianPeek/legoev3/blob/master/Testers/Lego.Ev3.Tester.Console/Program.cs
