### ISSUE TITLE
Non-Integer Turn Ratio in StepMotorSync

### ISSUE THREAD

**Issue by njsokalski** [BrianPeek/legoev3#27]
When using the StepMotorSync method, the turnRation parameter is of type Short (System.Int16), which is an integral value. How are we supposed to make the motors turn at ratios like 0.5, 1.25, etc.? The fact that it is of type Short obviously requires me to convert the value to a Short, which will cause rounding, almost defeating the purpose of having a ratio at all. Am I misunderstanding how this method is intended to be used? Thanks.

**Comment by BrianPeek** [comment]
Not possible...the parameter the brick is expecting is between -200 and 200 as an integer value.

**Comment by njsokalski** [comment]
I understand that, which is basically what my question was about. However, I think I managed to figure out how to do everything, but the documentation was very unclear about what the different values (or ranges of values) did, since it is not just a "ratio" of any numbers (it involved which direction, whether the ratio was A/B or B/A, etc.). The algorithm for finding the appropriate value was much more complex than I was expecting (I was expecting to just need A/B), but I guess I have to learn every part somehow.


Nathan Sokalski
njsokalski@hotmail.com<mailto:njsokalski@hotmail.com>
http://www.nathansokalski.com/


________________________________
