### ISSUE TITLE
Communication Classes Need Changed

### ISSUE THREAD

**Issue by njsokalski** [BrianPeek/legoev3#28]
I have been working on downloading and building the projects on my machine so that I can use them for my UWP apps (although I can't claim to have been very successful yet), but one thing that I found that needs updated (I don't know if it should be updated in the existing one or only in the new modified one for UWP) is the implementation of ICommunication in BluetoothCommunication.cs, NetworkCommunication.cs, and UsbCommunication.cs. All three of these, even though they have the methods that are supposedly not implemented (ConnectAsync & WriteAsync), implement the methods as IAsyncAction instead of Task. I would guess this would be a reasonably thing to fix, but since async and communication are probably two of my weakest areas (not to mention I am usually VB.NET rather than C#), I'm not sure if I should be the one to make these changes, but I am mentioning them to do the best I can to help get a UWP compatible version out as soon as possible.

**Comment by BrianPeek** [comment]
These already implement both Task or IAsyncAction depending on what you've #defined as the platform.
