### ISSUE TITLE
Lego Education Energy Meter not recognized

### ISSUE THREAD

**Issue by ddjidel** [BrianPeek/legoev3#35]
Hi,

I'm trying the sample app with my EV3. All sensors and motors are correctly recognized except the Energy Meter that is shipped with the Renewable Energy Add-on Set (https://education.lego.com/en-us/products/renewable-energy-add-on-set/9688).

Any chance you can help fixing this?

Thanks!

**Comment by BrianPeek** [comment]
I no longer own an EV3 and am not actively maintaining the source...sorry!

**Comment by ddjidel** [comment]
Ok, thanks. Updating the README would have made sense, then.
